---
- hosts: localhost
  collections:
    - netapp.ontap

  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: "{{ hostname }}"
      cert_filepath: name.pem
      key_filepath: name.key
      https: true
      validate_certs: false

  vars:
    - grid_admin_base_url: "https://grid-admin-url/"

  tasks:
    - include: tasks/get_tenantid_from_bucket.yaml
    - include: tasks/get_tenant_users.yaml
    - include: tasks/get_user_keys.yaml
